### ISSUE TITLE
Dependency 추가

### ISSUE THREAD

**Issue by seonuk** [TeamWeathy/WeathyServer#10]
# Dependency 추가

- winston : 에러 로그를 파일로 관리하므로 에러 대응에 용이
- swagger : api 명세 테스트 및 작성 용이
- sequelize : 관계형 디비와 노드의 패러다임을 통합하여 디비를 자바스크립트로 사용 가능
- eslint & prettier : 개발자간 코드 포맷 단일화

## 작업 브랜치
- `dev` <- `feature/#10/dependency`
## 추가할 dependency 목록
- Logger : winston 
- swagger
- sequelize
- eslint
- prettier

## 확인사항
- [x] dependency 추가
- [x] setting 파일 설정
- [x] 프로젝트 적용
- [x]  각 개발환경 설정

**Comment by seonuk** [comment]
# swagger 
- swagger-jsdoc: ^6.0.0,
- swagger-ui-express: ^4.1.6

# eslint & prettier
- eslint: ^7.16.0
- eslint-config-prettier: ^7.1.0
- eslint-plugin-prettier: ^3.3.0
- prettier: 2.2.1

## 사용
eslint, prettier extenstion 설치
저장 시 자동 포맷팅 원할 경우  
vscode setting 으로 설정
```
{
    // Set the default
    "editor.formatOnSave": false,
    // Enable per-language
    "[javascript]": {
      "editor.formatOnSave": true
    },
    "editor.codeActionsOnSave": {
      // For ESLint
      "source.fixAll.eslint": true
    }
  }
```

## 추가 설정
- airbnb 적용해봤으나 너무 엄격해서 불편해보여 우선 제거 해놨습니다
- 기본 eslint에서 몇 가지 저희한테 필요한 것만 설정하는게 좋아보입니다.
- 추가 : commit 시 eslint, prettier 포맷 형식 안따랐을 경우 commit 불가하게 하는 거 달까요?

# logger
- winston v3.3.3
- winston-daily-rotate-file v4.5.0

logs 디렉토리에 저장 
- production : 버전으로 시작 콘솔에 안찍힘, 파일 저장
- developement : 콘솔에 error, info 찍힘

**Comment by dshyun0226** [comment]
일단 서버 실행이후 루트 경로(http://localhost:3000/)로 접근하면 Express 페이지가 뜨는 것은 정상적으로 확인했습니다.
![image](https://user-images.githubusercontent.com/8098698/103436916-4d2a7200-4c64-11eb-8546-2bd82f9eb5e6.png)

추가적으로 각 라이브러리 별로 사용/테스트 방법에 대한 좀더 상세한 필요할 것 같아서 코멘트 남깁니다.
- Swagger (API 명세서 자동 생성)
  - 활용 보류
- ESLint (코드 포맷터)
  - VSCode 최신버전으로 설치 필요
  - 파일 저장시 자동 포맷팅 적용
- Winston (로거)
  - 서버 실행 전 환경변수(NODE_ENV)를 변경하여 모드 변경 가능
  - 기본 제공 모드
    - development
      - `$ export NODE_ENV development`
      - 별도의 환경변수 조작이 없을 때 기본으로 설정
      - 콘솔 + 파일 로깅 정책
    - production
      - `$ export NODE_ENV production`
      - 파일 로깅 정책

**Comment by dshyun0226** [comment]
@seonuk 확인 부탁드립니다

1. winston logger 테스트 코드 작성이 필요해보입니다.
    - development 모드일 때 콘솔 + 파일 로깅이 활성화 되는지
    - production 모드일 때 파일 로깅이 활성화 되는지
2. Express 미들웨어인 morgan 로거와 어떤 다른 사용처가 있는지 명확한 구분이 필요해 보입니다.

**Comment by seonuk** [comment]
@dshyun0226 

1. 우선 development 모드와 production 모드일 때 각각 돌려 테스트 해보긴했는데 성공했습니다.
    mocha나 다른 테스트용 라이브러리를 이용한 테스트 코드를 말씀하시는건가요? 
    이 부분에 대해서는 잘몰라서 자료 다시 찾아보고 말씀드리겠습니다!

2. morgan는 HTTP request에 관련된 로거입니다. 
    winston은 주로 로그를 파일로 기록하기 위한 로거입니다.
    morgan은 HTTP request의 로그를 위한 용도로,
    winston은 모든 에러와 인포 레벨에 대하여 일자별 파일에 기록하는 용도로 사용하려고 두 개의 모듈을 가지고 있습니다.

   * morgan이 winston의 역할을 대신 할 수도 있지만 일반적으로 winston과 함께 사용한다고합니다. morgan이 request를 포매팅해주는 미들웨어로 사용된다면 winston은 그 로그를 외부 파일에 저장하는 용도로 사용됩니다. 
   
ps.(속마음) 사실 request 로그에 대한 이득이 무엇인지는 잘안와닿아 지울까 생각도 해봤지만 express initialize에서 자동으로 설치하는 모듈이기도 하고 가벼운 모듈이기도 해서 냅뒀습니다... 죄송합니다 머리박겠습니다 ㅠㅠ

**Comment by dshyun0226** [comment]
@seonuk 요 이슈 닫을 수 있을 것 같은데 확인 후 닫아주세여!
