### ISSUE TITLE
기상청 API 분석

### ISSUE THREAD

**Issue by dshyun0226** [TeamWeathy/WeathyServer#4]
# 기상청 API 분석
> [공공데이터포털 동네예보 조회서비스 API](https://www.data.go.kr/data/15057682/openapi.do)

- 서비스에 사용할 날씨 정보를 기상청 API를 통해서 수집하려고 합니다ㅎㅎ (무료)
- 아래의 내용을 포함한 해당 API의 정보를 분석하고 검증할 필요가 있음
  - API 사용법
    - 사용 승인을 받는 법
    - 대표 예시 query 정리
  - 일자별로 획득 가능한 날씨 feature 리스트업
  - category의 각 코드가 무엇을 의미하는지 분석
  - 호출 가능한 기간, 지역, 등등

## 확인 사항
- [x] API로부터 획득 가능한 날씨 feature 기획팀 전달
- [x] API 사용법 및 시연 서버팀 내 공유

**Comment by seonuk** [comment]
기상청 api 분석 & open weather api 추가

개인적인 의견으로는 기상청 api는 완전 무료인데 호출하여 사용하기도 까다롭고(하루 공급되는 데이터 양이 많고 불규칙함), 공급되는 데이터들이  웨디의 방식에 적합하지않을 수도 있어보입니다(최고 온도, 최저 온도 제공, 체감 온도 X, 아침 최고온도, 저녁 최고온도 이런 형식으로 제공)

open weather는 사용하기 편리하고 공급되는 데이터도 알맞으나 무료로 사용할 경우 제약이 살짝 존재합니다. (무료 버전 최대 7일 뒤까지만 제공) 하지만 앱잼 기간내 사용에는 무리가 없어보입니다. 

따라서 open weather 사용이 더 적합해보이는데 의견이 어떠신지 여쭤봅니다. 

참고로 두개다 과거 시간에 대한 정보는 제공해주지 않습니다.

**Comment by dshyun0226** [comment]
> 참고로 두개다 과거 시간에 대한 정보는 제공해주지 않습니다.

과거의 시간대별로 정보를 제공해주지는 않는다는 뜻이겠죠? 현재기획상에서 문제가 되지 않을 듯 하고,,

> 무료 버전 최대 7일 뒤까지만 제공

7일 이후 미래의 날씨 온도를 가져오지 못하는것 또한 현재 기획에서는 문제가 없을 듯 합니다 ㅎㅎ

다만 추가로 확인이 필요할 것 같은 항목은 openweather에서 (@seonuk )
- 하루에 1000번, 한달에 100만번 호출가능한데 이것을 초과할 경우 자동 과금이 되는 방식인지 혹은 response가 안오는 방식인지?
- 요청이 있을때마다 openweather로 api 호출하는것은 비효율적일 것 같아서 주기적으로 백업받는 방식이 좋을 것 같은데 혹시 xls, csv 형식으로 전체 데이터를 제공하고 있지는 않은지?

궁금합니다!

**Comment by seonuk** [comment]
>  이것을 초과할 경우 자동 과금이 되는 방식인지 혹은 response가 안오는 방식인지  

무료 계정일 경우 api call의 개수를 줄이거나 plan을 변경하라고 알린 뒤 아무 조치가 없을 경우 계정을 자동으로 차단한다고 합니다. 
즉, 요청이 초과될 경우 과금은 없고 api 사용은 불가능합니다.  

유료 계정의 경우는 자동으로 차단되는 경우는 없고 함께 적합한 계정을 찾아준다고 합니다 

추가로 유료계정 사용할 경우는 다음과 같은 사항이 있습니다.
- Visa®, MasterCard®, American Express®, Maestro®, JCB®, Union Pay®. 카드 필요
- 매월 자동 납부, 어떠한 이유로 자동 납부 실패 시 5일동안 자동으로 다시 납부를 시도 3번 실패 시 계정이 정지됨  
  
  

  
  
> 혹시 xls, csv 형식으로 전체 데이터를 제공  

찾아보니깐 다운로드 파일로 현재 날씨와 예측된 날씨 json 형태로 가져올 수 있습니다.  
 다만 모든 나라의 데이터를 가져와서 21만개의 데이터 중 한국의 데이터만 뽑아와야합니다. 데이터는 UTC 기준으로 한시간마다 갱신된다고 합니다. 무료 플랜에서 사용가능합니다. 

  
예시
```json
{"city":{"id":1832384,"name":"Eisen","findname":"EISEN","country":"KR","coord":{"lon":128.630829,"lat":36.821671},"zoom":10},"time":1554462344,"main":{"temp":281.15,"pressure":1007,"humidity":36,"temp_min":281.15,"temp_max":281.15},"wind":{"speed":3.6,"deg":250},"clouds":{"all":1},"weather":[{"id":800,"main":"Clear","description":"clear sky","icon":"01n"}]}
{"city":{"id":1832501,"name":"Reiko","findname":"REIKO","country":"KR","coord":{"lon":126.509438,"lat":35.275002},"zoom":10},"time":1554462344,"main":{"temp":284.15,"pressure":1012,"humidity":53,"temp_min":284.15,"temp_max":284.15},"wind":{"speed":3.6,"deg":330},"clouds":{"all":20},"weather":[{"id":801,"main":"Clouds","description":"few clouds","icon":"02n"}]}
```
  
추가로 
> 참고로 두개다 과거 시간에 대한 정보는 제공해주지 않습니다.

이 항목 다시 찾아보니 open weather에서 과거 날씨를 제공해줍니다. 파일 형식 그리고 api 호출 형식 둘 다 지원해주고 무료 플랜에서 사용 가능합니다.


----
개인 의견
- Open weather api를 통해 무료 플랜으로 현재까지 이해한 기획은 모두 가능할 것으로 예상됩니다 그리고 예외적인 상황이나 추가되는 기능을 고려할 때에도 open weather api가 기상청에 비해 훨씬 많은 데이터를 제공해주고 있어 open weather를 사용하는게 좋아보입니다!  

>  api 호출하는것은 비효율적일 것 같아서 주기적으로 백업받는 방식이 좋을 것 같은데  
 
동의합니다.
저도 cron이나 scheduler와 같은 노드 batch 모듈 활용해서 데이터를 주기적으로 갱신하는 방법 좋아보입니다!    
다만 사용자가 날씨를 알기 원하는 동네라는 개념을 명확히 해야할 것 같습니다. 만약 단순 위도 경도로 한다면 가져온 대용량 파일에서 일치하는 것이 없을 때 동네를 결정하는 정책이 필요할 것 같습니다


@dshyun0226 @yxxshin

**Comment by yxxshin** [comment]
> Open weather api를 통해 무료 플랜으로 현재까지 이해한 기획은 모두 가능할 것으로 예상됩니다 그리고 예외적인 상황이나 추가되는 기능을 고려할 때에도 open weather api가 기상청에 비해 훨씬 많은 데이터를 제공해주고 있어 open weather를 사용하는게 좋아보입니다! 

저도 이와 동일한 입장으로 Open Weather API를 사용하는 것에 동의합니다! 

> cron이나 scheduler와 같은 노드 batch 모듈 활용해서 데이터를 주기적으로 갱신하는 방법

동의합니다 !

> 다만 사용자가 날씨를 알기 원하는 동네라는 개념을 명확히 해야할 것 같습니다. 만약 단순 위도 경도로 한다면 가져온 대용량 파일에서 일치하는 것이 없을 때 동네를 결정하는 정책이 필요할 것 같습니다

요건 기획파트에게 오늘 물어보면 될 것 같습니다.. 개인적으로 위도 경도보다 '동'의 개념으로 하는 것이 날씨 데이터 가져오기도 편하고, 예외 사항도 없을 것 같은데 맞나요? 같은 동네 안에서 날씨가 드라마틱하게 바뀔 것 같지도 않구요.

**Comment by dshyun0226** [comment]
### 행정구역별 위치 좌표
~~[서울시군구_위도경도.xlsx](https://github.com/TeamWeathy/WeathyServer/files/5747694/_.xlsx)~~
~~[전국 행정시군구동읍면리 위도경도.xlsx](https://github.com/TeamWeathy/WeathyServer/files/5752943/default.xlsx)~~
[전국 행정시군구 위도경도.xlsx](https://github.com/TeamWeathy/WeathyServer/files/5750746/default.xlsx)
