### ISSUE TITLE
Batch 데이터 받아올 때 4분 가량 DB에 접근할 수 없는 문제

### ISSUE THREAD

**Issue by yxxshin** [TeamWeathy/WeathyServer#40]
# Batch 데이터 받아올 때 4분 가량 DB에 접근할 수 없는 문제

### 발생 환경
- 하루에 한 번씩 Batch에서 데이터를 받아올 때 4분 가량 DB에 접근할 수 없음.

### 기대 내용
- 앱잼 이후, View / Update 나누는 기능 이용하여 해결할 예정.
- 2021.01.12. 기준 서버 배포 ver로는 사용할 수 없음.

**Comment by seonuk** [comment]
디비에 업데이트하는 시간이 아니라 데이터를 받아오는 시간이였습니다 ㅎㅎ 십만개 아래의 데이터를 업데이트 하는거라 크게 신경 안써도 될 듯 합니다.
