### ISSUE TITLE
API 명세서 작성

### ISSUE THREAD

**Issue by dshyun0226** [TeamWeathy/WeathyServer#6]
# API 명세서 작성

- 클라이언트 팀과 와이어프레임 보면서 각 뷰별로 제공이 필요한 데이터 리스트업
- API 명세서 작성
  - (Request) URI, method, headers, body
  - (Response) headers, body, code(status, error)

## 확인 사항
- [x] WIKI [API 명세서](https://github.com/TeamWeathy/WeathyServer/wiki/API-%EB%AA%85%EC%84%B8%EC%84%9C)
- [x] 대락적인 ERD까지 고려해서 설계할 필요가 있음
- [x] 클라이언트 팀의 검수

**Comment by yxxshin** [comment]
중간 과제 제출 완료 [API 명세서](https://github.com/TeamWeathy/WeathyServer/wiki)
[뷰 별 API_0106ver.pdf](https://github.com/TeamWeathy/WeathyServer/files/5771858/API_0106ver.pdf)
