### ISSUE TITLE
Calendar Api Response type, stampId 누락

### ISSUE THREAD

**Issue by seonuk** [TeamWeathy/WeathyServer#65]
# Calendar Api Response type, stampId 누락

## 개요
api 명세서의 Calendar Api response 변수와 실제 response가 다른 이슈 발생 (stampId가 누락되어 나타남)

### 발생 환경
- Api 콜하는 모든 경우

### 기대 내용
- 캘린더 response type이 정상적인 상황에서는 다음과 같아야 합니다.

```json
{
    "calendarOverviewList": [
        {
            "id": 1,
            "stampId": 3,
            "temperature": {
                "maxTemp": 4,
                "minTemp": -3
            }        
       },
       null,
       null,
       ...
    ],
    "message": "캘린더 월 정보 조회 성공"
}
```

### 현재 내용
- response가 다음과 같이 옵니다.
```json
{
    "calendarOverviewList": [
        {
            "id": 1,

            "temperature": {
                "maxTemp": 4,
                "minTemp": -3
            }        
       },
       null,
       null,
       ...
    ],
    "message": "캘린더 월 정보 조회 성공"
}
```
- stampId가 누락되어 나타납니다.

## 레퍼런스
- 버그가 발생했을 때의 스크린샷, 로그 등을 첨부해주세요.

## 해결
- [x] CalendarService.js 내 stampId 변수를 데이터 베이스 타입인 emoji_id로 변경
- [x] 소스 작성자 컨펌

**Comment by seonuk** [comment]
[HOTFIX]로 현재 CalendarService.js 내 stampId를 emoji_id로 변경하여 서버에 반영해놨습니다.
크게 문제없어 보이지만 혹시 모르니 확인 한번 해주세요!
@dshyun0226

**Comment by dshyun0226** [comment]
확인했고 이슈 닫도록 하겠습니다~
