### ISSUE TITLE
WeatherController 파라미터 에러

### ISSUE THREAD

**Issue by seonuk** [TeamWeathy/WeathyServer#66]
# WeatherController 파라미터 에러

## 개요
keyword로 지역 검색 시 파라미터에서 발생한 에러를 검출하지 못했습니다.

### 발생 환경
- Ios 

### 기대 내용
- 잘못된 요청이 왔을 때 클라이언트에게 메세지를 보내줍니다.

### 현재 내용
- 클라이언트가 요청에 대한 반환값을 받지 못했습니다.
- 클라이언트가 잘못된 요청을 보낸 상황입니다.

## 레퍼런스
<img width="1152" alt="스크린샷 2021-01-14 오전 8 38 18" src="https://user-images.githubusercontent.com/22928068/104525633-dd44c000-5643-11eb-86e7-7f7abcad974c.png">

**Comment by seonuk** [comment]
현재는 큰 문제는 없습니다만 혹시나 해서 미리 적어놓습니다.

**Comment by dshyun0226** [comment]
클라이언트에서 보내는 date의 포멧이 잘못되었을 때 발생하는 문제 같아 보이네요.
TypeError를 catch하도록 코드를 수정하면 좋을 것 같으나, 추후에 문제가 생기면 하도록 하겠습니다 ㅎㅎ

**Comment by seonuk** [comment]
https://github.com/TeamWeathy/WeathyServer/issues/66#event-4364704714
