### ISSUE TITLE
Clothes 부분을 보완한 3001번 포트 서버 개발

### ISSUE THREAD

**Issue by yxxshin** [TeamWeathy/WeathyServer#67]
# Clothes 부분을 보완한 3001번 포트 서버 개발

- 발견된 버그 사항과 기획 변동 사항을 적용한 새로운 서버 개발
- 새로운 서버는 3001번 포트에 올려 두고, 기존 서버의 3000번 포트와 함께 돌려 놓기

## 변경 사항
- '현재' 옷장의 옷 개수를 전달하여야 함.
- 과거의 웨디 조회 시, 그 당시 웨디의 옷을 전달하여야 함.
  - 삭제된 옷이더라도 볼 수 있어야 하고, 삭제된 옷이어도 등록이 가능해야 함.
- 표시되는 옷의 개수는 기획파트로부터 전달 받을 것. 
  - (수정) '현재' 옷장의 옷 개수를 표시하면 된다.
- Clothes API 명세서 참고
  - 세 API에 `clothesNum` 변수 추가
  - GET Clothes API에 optional한 param `weathyid` 추가

## 수정해야 할 내용들
- 옷장의 옷 개수를 보내주기 (세 API)
- GET Clothes API에 optional한 param `weathyid` 고려하기
  -  현재 옷들 + `weathyid`에 작성되었던 옷들을 보여주어야 함
- 삭제된 옷이면 Weathy 등록이 불가능한 부분 수정 (`clothesService` 등)

## 작업 브랜치
- `dev` <- `feature/#67/clothes-new-server`

## 확인 사항
- [x] API 명세서 수정
- [x] unit test 성공 확인
- [x] 3001 포트 열고 배포

**Comment by dshyun0226** [comment]
배포 했으므로 close 합니다!
