### ISSUE TITLE
Weathy 사진 저장 기능 추가

### ISSUE THREAD

**Issue by seonuk** [TeamWeathy/WeathyServer#69]
# Weathy 사진 저장 기능 추가

- weathy 사진 저장 신규 기능 추가
- weathy 기록 또는 수정 시 `한장의 사진`을 추가할 수 있는 기능

## 작업 브랜치
- `dev` <- `feature/img`

## 확인 사항
- [x] 파일 저장 위치 (s3, 로컬 저장소)
- [x] 사진 수정 시 클라와 협의
- [x] 데이터 베이스 설계
- [x] weathy 관련 Api 명세서 수정
- [x] 파일 업로드 코드 구현

**Comment by dshyun0226** [comment]
이 이슈는 pr merge 되었으므로 close 하겠습니다.
