### ISSUE TITLE
데이터베이스 연결 라이브러리 추가

### ISSUE THREAD

**Issue by dshyun0226** [TeamWeathy/WeathyServer#7]
# 데이터베이스 연결 라이브러리 추가

- AWS RDS와 연동하여 데이터 입력/조회/수정/삭제를 위한 라이브러리 의존성 추가
- 데이터 베이스 계정 정보
  - **절대 공유하면 안됨**

## 작업 브랜치
- `dev` <- `feature/#7/connect-db`

## 확인 사항
- [x] db_config 파일 작성
- [x] models 정의
- [ ] 테스트 코드 추가

**Comment by seonuk** [comment]
- 모델 정의 완료
- Weathies, WeathyClothes => paranoid: false (실제 삭제됨 + cascade) 
- 나머지 테이블 => paranoid: true
